import type { PhotoSeries } from '@/types/photoSeries';

/** Placeholder featured series — wire Sanity query later. */
export const FEATURED_SERIES: PhotoSeries[] = [
  {
    title: 'Rajasthan',
    slug: 'rajasthan',
    coverImage: 'https://picsum.photos/seed/rajasthan/600/800',
    category: 'Travel',
    year: '2023',
    frameCount: 24,
    featured: true,
    order: 1,
  },
  {
    title: 'Monsoon',
    slug: 'monsoon',
    coverImage: 'https://picsum.photos/seed/monsoon/600/800',
    category: 'Documentary',
    year: '2022',
    frameCount: 18,
    featured: true,
    order: 2,
  },
  {
    title: 'Coastal Light',
    slug: 'coastal-light',
    coverImage: 'https://picsum.photos/seed/coastal/600/800',
    category: 'Landscape',
    year: '2024',
    frameCount: 32,
    featured: true,
    order: 3,
  },
  {
    title: 'Night Market',
    slug: 'night-market',
    coverImage: 'https://picsum.photos/seed/nightmarket/600/800',
    category: 'Street',
    year: '2023',
    frameCount: 21,
    featured: true,
    order: 4,
  },
  {
    title: 'Portraits',
    slug: 'portraits',
    coverImage: 'https://picsum.photos/seed/portraits/600/800',
    category: 'Portrait',
    year: '2021',
    frameCount: 16,
    featured: true,
    order: 5,
  },
  {
    title: 'Himalaya',
    slug: 'himalaya',
    coverImage: 'https://picsum.photos/seed/himalaya/600/800',
    category: 'Travel',
    year: '2024',
    frameCount: 28,
    featured: true,
    order: 6,
  },
].sort((a, b) => a.order - b.order);
