import type { PhotoSeries } from '@/types/photoSeries';

/** Placeholder featured series — wire Sanity query later.
 *  Dimensions vary on purpose so the native-aspect hero is visible without Sanity. */
export const FEATURED_SERIES: PhotoSeries[] = [
  {
    title: 'Rajasthan',
    slug: 'rajasthan',
    coverImage: 'https://picsum.photos/seed/rajasthan/1200/800',
    coverAspectRatio: 1.5,
    category: 'Travel',
    year: '2023',
    frameCount: 24,
    featured: true,
    order: 1,
  },
  {
    title: 'Monsoon',
    slug: 'monsoon',
    coverImage: 'https://picsum.photos/seed/monsoon/800/1000',
    coverAspectRatio: 0.8,
    category: 'Documentary',
    year: '2022',
    frameCount: 18,
    featured: true,
    order: 2,
  },
  {
    title: 'Coastal Light',
    slug: 'coastal-light',
    coverImage: 'https://picsum.photos/seed/coastal/1600/900',
    coverAspectRatio: 1.7778,
    category: 'Landscape',
    year: '2024',
    frameCount: 32,
    featured: true,
    order: 3,
  },
  {
    title: 'Night Market',
    slug: 'night-market',
    coverImage: 'https://picsum.photos/seed/nightmarket/800/1100',
    coverAspectRatio: 0.7273,
    category: 'Street',
    year: '2023',
    frameCount: 21,
    featured: true,
    order: 4,
  },
  {
    title: 'Portraits',
    slug: 'portraits',
    coverImage: 'https://picsum.photos/seed/portraits/800/1000',
    coverAspectRatio: 0.8,
    category: 'Portrait',
    year: '2021',
    frameCount: 16,
    featured: true,
    order: 5,
  },
  {
    title: 'Himalaya',
    slug: 'himalaya',
    coverImage: 'https://picsum.photos/seed/himalaya/1400/900',
    coverAspectRatio: 1.5556,
    category: 'Travel',
    year: '2024',
    frameCount: 28,
    featured: true,
    order: 6,
  },
].sort((a, b) => a.order - b.order);
